### ISSUE TITLE
EnterpriseEventsAsync fails with non null createdAfter parameter

### ISSUE THREAD

**Issue by Dave-Lowndes** [box/box-windows-sdk-v2#361]
Using this code:

` DateTime? dt = DateTime.Now;
 EnterpriseEventsAsync( 500, null, null , dt );
`

Gives rise to a  BoxException "Invalid created_after parameter"

if dt is null, it succeeds.

My time zone is UK (currently +1), so the resultant string for the time parameter becomes:
    "2017-07-13T10:19:04+01:00"

I note the same problem was raised in issue #310 and appears to be closed.

**Comment by Dave-Lowndes** [comment]
If I change my machine's time zone to US Pacific time, the result of formatting the time to a string as the underlying code does

dt.Value.ToString("yyyy-MM-ddTHH:mm:sszzz")

produces: "2017-07-13T04:08:40-07:00"

and the call succeeds!

**Comment by coolboy** [comment]
Hi @Dave-Lowndes ,

Could you show me the full exception message and the raw request/response?

Are you seeing an exception like below?
BoxException: {"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"created_after is invalid since it is in the future","request_id":"12088466945967d1341941d"}

**Comment by coolboy** [comment]
For the failed request with `2017-07-13T10:19:04+01:00` , what's the time as of that time?

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

I don't have the full exception at hand, but it specifically included the text "Invalid created_after parameter"; not the text you showed.

As for the time I gave, it was that time today UK (13'th July 2017 11:19 AM) - we're currently UTC+1hr. Is that what you were asking me?

Report #310 looks to be exactly the same issue as far as I can see.

**Comment by coolboy** [comment]
Hi @Dave-Lowndes ,

OK I could repo your problem here
The request succeed with `2017-07-13T10:19:04-07:00` but failed with '2017-07-13T10:19:04+01:00'

And the error is 

`{"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Invalid created_after parameter","request_id":"5399571275967dfaea1670"}`

**Comment by coolboy** [comment]
Our SDK is passing through, so the root cause here should be on the API side, I will fwd this to the team to see if they can find out why

**Comment by Dave-Lowndes** [comment]
Great, thanks for the prompt feedback. We'd love to see this fixed.

**Comment by coolboy** [comment]
@Dave-Lowndes 

Ok, the fix is ready here, https://github.com/box/box-windows-sdk-v2/pull/364

The root cause is that we forget to url encode the datetime string in the url -_-

**Comment by Dave-Lowndes** [comment]
@coolboy Are there any plans to get a new version released such that we can pick it up easily in Visual Studio using the NuGet facility? The latest version available there is 2.15.6 from May 25'th 2017.

**Comment by coolboy** [comment]
@Dave-Lowndes 

We are planing to release a new version in next few weeks

And also the new release will be a major version bump (3.0.0 I believe), since we are dropping Portable Class Library and with net45 this time

Let me know if you have any concern

**Comment by Dave-Lowndes** [comment]
@coolboy We should be OK with those plans.
Thanks.
