### ISSUE TITLE
Box API Rate limits and how this SDK handles it

### ISSUE THREAD

**Issue by JazzyFizzles** [box/box-windows-sdk-v2#362]
Hi,
The Box forum mentions:
https://community.box.com/t5/Box-Developer-Forum/FAQ-Box-Platform-and-APIs/m-p/14768#U14768
"What are the rate limits around the API?
There are two limits. The first is a limit of 10 API calls per second per user. The second limit is 4 uploads per second per user."

How is the Box API limit handled by this SDK?
Is an Exception thrown?

Thanks,

**Comment by coolboy** [comment]
Hi @JazzyFizzles 

Basically we will retry 3 times.

What's your use case here? Why do you want to know more about it? More context may help me answer your question better.

If we get a 429 error code and this is not a multi part request (meaning a file upload, which cannot be retried
because the stream cannot be reset) and we haven't exceeded the number of allowed retries, then retry the request.
If we get a 202 code and has a retry-after header, we will retry after

Please find the code here
https://github.com/box/box-windows-sdk-v2/blob/f8478d95006092498eaa5553cf369140d32210f5/Box.V2/Request/HttpRequestHandler.cs#L78

**Comment by JazzyFizzles** [comment]
Thanks for your reply coolboy.

I’m involved with a project aimed at businesses of which is a requirement to check each user uploaded file and if a user makes a change to the metadata of that file. We expect to hit the Box API rate limits and want to ensure we correctly handle it.

More questions relating to the code you linked to:
1) for clarification, it appears that your SDK hides us from hitting the Box API rate limit. Is this correct?
2) line 84 “(response.StatusCode == HttpStatusCode.Accepted && retryAfterHeader != null))” in what case would there be a retryAfterHeader – the specification for Http Status Code Accepted (202) doesn’t indicate a retry after response – see [https://tools.ietf.org/html/rfc7231#section-6.3.3](url)

**Comment by coolboy** [comment]
Hi @JazzyFizzles 

Thank you for using Box to drive your business! and please find my answers below:

1. We will retry 3 times in 2 seconds (if retryAfterHeader is not specified) interval.
When all failed, we will throw exception according to the response of the last request.

2. This is how we designed some of our APIs
You can find an example here https://developer.box.com/reference#get-a-thumbnail-for-a-file

`If the thumbnail isn’t available yet, a 202 Accepted HTTP status will be returned, including a Location header pointing to a placeholder graphic that can be used until the thumbnail is returned. A Retry-After header will also be returned, indicating the time in seconds after which the thumbnail will be available. Your application should only attempt to get the thumbnail again after Retry-After time.`

Let's know if what we have is not enough for your use case, and we can begin from there.

**Comment by Dave-Lowndes** [comment]
Hi @Coolboy,

I work with @JazzyFizzles and we're investigating our service when it has a large workload.

We handle everything async and are finding that we frequently get a BoxException thrown with a "rate_limit_exceeded" error code.

Currently we've identified that we're getting those exceptions from calling BoxFilesManager.GetInformationAsync, BoxFilesManager.DownloadStreamAsync, and BoxMetadataManager.GetFileMetadataAsync.

Consequently, we're thinking that we'll have to wrap all our Box API calls in our own try/catch (for that specific error) in order to perform additional Task.Delay/retries - which subsequently seem to succeed.

We don't think we should have to do this.

Why did you decide to limit your internal retries to 3 times rather than retrying (whenever possible) for as long as the service returns you that situation?

**Comment by coolboy** [comment]
Having unlimited retry as default behavior in the SDK is very dangerous and may lead to DDOS Box servers in my opinion.

We already have similar site issues in the past of our other services.

I am not the original creator for the 3 times retry logic in the SDK, but I believe this is the reason.

@JazzyFizzles @Dave-Lowndes

**Comment by Dave-Lowndes** [comment]
Hi @coolboy,

I appreciate what you say about potential DDOS attacks, but surely that's the responsibility of the underlying Box web service, not an intermediate SDK interface. After all, if someone wanted to conduct a DDOS, they would bypass this interface and hit the web service directly.

Is there a way to check with the originator of the retry logic to follow up on this as it's not effective in our load testing.

**Comment by coolboy** [comment]
loop in @cburnette to see if he has more context on this.

**Comment by coolboy** [comment]
BTW, we are going to have Batch API support, which will allow you to group up to 20 requests into one call, and only count as 1 API call

I don't have an ETA yet, but it's coming

**Comment by Dave-Lowndes** [comment]
@coolboy The batch interface sounds interesting, but I suspect we won't be able to make use of it for what we're doing - we'll have a look at it when we can see it.
@cburnette Do you have any comment on the query I've raised here about the retry count?

**Comment by coolboy** [comment]
closing due to last activity is more than 30 days
