### ISSUE TITLE
Why is BoxItem PathCollection null?

### ISSUE THREAD

**Issue by Chiliyago** [box/box-windows-sdk-v2#383]
When iterating through the BoxItems after executing the GetFolderItemsAsync() method the property PathCollection is always null.  Why is that?

**Comment by coolboy** [comment]
Please find our reference doc here -> https://developer.box.com/v2.0/reference#get-a-folders-items

Any attribute in the full files or folders objects can be passed in with the fields parameter to get specific attributes, and only those specific attributes back; otherwise, the mini format is returned for each item by default. Multiple attributes can be passed in separated by commas e.g. fields=name,created_at.

In here, it will be fields=path_collection
