### ISSUE TITLE
Autopaginate causes Powershell GUI forms to hang when set to $true

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#432]
I have a powershell GUI form project which will search for and delete the box account associated with a designated Active Directory object when a button is clicked.  When the button is clicked and I set the "autopaginate" value to $true when trying to retrieve a list of enterprise users (assuming that a valid admin client object is assigned to the value "$adminclient", the command would look like "$adminclient.UsersManager.GetEnterpriseUsersAsync($null, 0, 1000, $null, $null, $null, $true)"), the entire form locks up (either when I use the "wait()" method to get the script to wait for the above process to finish before continuing or when I try to access the "result.entries" property of the return.  However, if I change the "autopaginate" value to "$false" when running the command, it processes normally.  Furthermore, if I copy and past the problem code into a separate Powershell file and run the code (with the "Autopaginate" value set to $true) as a console application (no GUI), the command will also run perfectly.  This issue only occurs when the autopaginate argument for a box windows sdk method is set to $true when it is run in a powershell form.  I am fully aware that there is a way to get all of the results that are needed while keeping the autopaginate set to $false, but I would like to keep the code as short as possible without having to write out a "do  While" loop for each and every data retrieval I perform.  For Gui which hangs as well as script with same code copy pasted which works posted in txt format.  Also attached a dll necessary for script to integrate with AD (remove the ".txt" from end to return to normal).  To see a live demonstration (as apparently you don't like trying to run the example scripts that are submitted to you), please take a look at the video at one of the below links:
https://youtu.be/AbO5x7n-6GY
https://acuitybrandsinc-my.sharepoint.com/personal/wmh02_acuitysso_com/_layouts/15/guestaccess.aspx?docid=05cdfbf0413994625a3c24b2f0c71cdc0&authkey=AY-oVB24XWcD4iSlqy6cEnk&e=br1vs5
https://vimeo.com/250060043

[thefiles.zip](https://github.com/box/box-windows-sdk-v2/files/1610509/thefiles.zip)

**Comment by mattwiller** [comment]
Hi @whiggs — we're looking into this issue, but it may take us a while to get a development environment set up to accurately debug the problem since we do not generally use Powershell GUI here at Box.  If there's any more information you can give us about this issue, it would be very helpful.

**Comment by whiggs** [comment]
I understand.  Thats ok.  I have mentioned this to a box support rep, but seeing as the box windows sdk is not developed to be used in powershell sessions, and considering that powershell is a extremely popular scripting language, I think it would make a lot of people happy if box would release an officially supported box powershell module.  I am aware there is an unofficial one, but it is very lacking in what it can do (eg. does not support OAuth 2.0 with JWT authentication, which is pretty much the entire reason I needed to use an sdk in the first place, as I can just make calls to the api directly to accomplish everything else I would need.

**Comment by mattwiller** [comment]
Thanks for understanding @whiggs — we'll add this to our backlog, but since there's a workaround available (manually looping through the collection) and this seems to only be a problem in one environment (Powershell), work on this may be scheduled after other high-priority work our team is taking on.

To help us out when we do work on it, could you please provide the versions of PowerShell, .NET Core, and the Box SDK that you're using?

**Comment by whiggs** [comment]
Ok.  I would just say the latest of each, but that is probably not what you want to hear.
For the box sdk, every time the script is run, it uses the nuget command line tool to pull the latest version of the box sdk from nuget.
.net core sdk v. 2.1.4
And the highest version of powershell available, 5.1, as this is running on Windows 10 version 1703

**Comment by mattwiller** [comment]
@whiggs I tried reproducing the issue with a stripped-down test case based on the PowerShell script you sent (using a Developer Token instead of JWT auth, working against a test enterprise with just a handful of users in it), and it worked fine for me.  I tried setting the `limit` value in `GetEnterpriseUsersAsync()` to 1000 (what your script used) , and to 1 (to force it to make multiple API calls, since I only have a few users in my test enterprise), but in both cases it did fetch all the users for me with `autoPaginate` set to `$true` in my PowerShell script.

I'm wondering if this is maybe some sort of rate limiting or other related issue — since [the autopagination functionality in this method](https://github.com/box/box-windows-sdk-v2/blob/43b2af689b2c0da6c77b420bd98ad2c88e867069/Box.V2/Managers/BoxResourceManager.cs#L144) just makes as many calls as necessary to fetch the entire data set before the Task resolves, it may end up making many calls, each of which might not be very fast.  If it ends up making too many calls, it may end up hitting rate limits on the Box API, which would cause it to take even MORE time as the requests retry.

With that in mind, what sort of scale are you working with here?  About how many managed users does your enterprise have, and so how many requests might this code be making behind the scenes?
