### ISSUE TITLE
Download fails after 4-6 files are downloaded

### ISSUE THREAD

**Issue by JaideepSingh2018** [box/box-windows-sdk-v2#440]
Hello,

We are writing a console application that download files from users's Box account. We can download 4-6 files without any problems but after that Box API doesn't returns the contents. It waits for around 90 seconds and Thread that's executing the download gets cancelled. If we rerun the program it will down next 4-6 files and it will stop working.

Sample Code: Line in bold 
![whatsapp image 2018-01-24 at 12 17 40 pm](https://user-images.githubusercontent.com/35810540/35399154-dd231dbe-01b0-11e8-8b7b-a35658ed410f.jpeg)
doesn’t give any response after downloading 4 files

private async Task<int> Run()
{
            BoxClient userClient=await InitializeConnection();
            BoxFolder root = await userClient.FoldersManager.GetInformationAsync("0");
            List<string> allFiles=await ListFolder(root, userClient,null);
 
                foreach (string file in allFiles)
              {
                    try
                    {
                 
                                               Download(file, true, userClient);
                       
                       }
                              catch (Exception ex)
                              {
 
                                             if (ex.Message.ToLower().Contains("canceled"))
                                             throw ex;
                             }
                       }
   }
 
 
    private async Task Download(string fileId,  bool isFile,BoxClient client)
        {
            BoxFile fileInfo=null;
            try
            {
                fileInfo = await client.FilesManager.GetInformationAsync(fileId);
                ExternalDocumentEntity eDoc = new ExternalDocumentEntity();
                eDoc.Path = folder;
                eDoc.Id = fileInfo.Id;
           
                eDoc.Description = fileInfo.Description;
                if (fileInfo.VersionNumber != null)
                {
                    eDoc.ChangeInformation = fileInfo.VersionNumber.ToString();
                 
                }
                eDoc.ContentHash = fileInfo.FileVersion.Sha1;
                eDoc.CreatedBy = fileInfo.CreatedBy.Login;
                eDoc.CreatedDate = fileInfo.CreatedAt.Value;
                eDoc.ModifiedBy = fileInfo.ModifiedBy.Login;
                eDoc.ModifiedDate = fileInfo.ModifiedAt.Value;
                //If file is locked by the user on Box
                if (fileInfo.Lock != null)
                {
                    eDoc.LockedBy = fileInfo.Lock.CreatedBy.Login;
                    eDoc.LockedDate = fileInfo.Lock.CreatedAt.Value;
                }
 
                //Do not read the content if checksum value is same. If the file doesnt exist in TINA it will return 0
                if (!ExternalData.GetInstance(clientName).IsFileChanged(fileInfo.Id, eDoc.ContentHash, clientName))
                {
                    **Extensions.ReadAllBytes(await client.FilesManager.DownloadStreamAsync(fileId));****
                }
               
                eDoc.FileSize = (ulong)fileInfo.Size.Value;
              
                
                //eDoc.IsDeleted = fileInfo.Type.
                if (isFile)
                    eDoc.IsFile = isFile;
                else
                    eDoc.IsFolder = isFile;
                eDoc.SharedFolderId = fileInfo.Parent.Id;
                eDoc.Name = fileInfo.Name;
                eDoc.FileExtension = Path.GetExtension(fileInfo.Name);
                eDoc.FileURL = boxRoot + fileInfo.Id;
                eDoc.NetworkName = networkName;
          
           
            }
            catch (Exception ex)
            {
                EventLog.WriteEntry("Tina5s.Connector", "Unable to download file:"+ fileInfo.Name+":"+ex.Message + ex.StackTrace);
                throw ex;
            }
          
 
        }

**Comment by mattwiller** [comment]
Hi @JaideepSingh2018 — thank you for the detailed bug report!  We'll start investigating and let you know what we find out.

**Comment by carycheng** [comment]
Hey @JaideepSingh2018, 

We observed that these cancellation errors can happen when a stream sits for a long time without any bytes being actively read from it. 

If possible, can you share what Extensions.ReadAllBytes() is doing in your example?  

We were able to download all 211 items from a folder successfully with the following code like the following: 

```c#
BoxCollection<BoxItem> items;
System.Collections.Generic.List<BoxItem> folderItems;

items = await _client.FoldersManager.GetFolderItemsAsync("FOLDER_ID", 500);
folderItems = items.Entries;

foreach (BoxItem file in folderItems)
{
    byte[] buffer = new byte[file.Size];
    long position = 0;
    
    var stream = await _client.FilesManager.DownloadStreamAsync(file.Id);
    var numBytesRead = 1;
    
    /// Read from the stream one kB at a time. 
    while (numBytesRead > 0)
    {
        numBytesRead = stream.Read(buffer, position, 1024);
        position += numBytesRead;
    }
    /// buffer should now contain the file.
}
```

If you could look into how you are reading from the stream and let us know if you run into anymore issues. Thanks!

**Comment by JaideepSingh2018** [comment]
Thank you for looking into it. Please find the code below for Read All Bytes 
public static byte[] ReadAllBytes(this Stream instream)
        {
            if (instream is MemoryStream)
                return ((MemoryStream)instream).ToArray();

            using (var memoryStream = new MemoryStream())
            {
                instream.CopyTo(memoryStream);
                return memoryStream.ToArray();
            }
        }

**Comment by JaideepSingh2018** [comment]
I have copy pasted your code as is and I am getting the same error after 6 files

**Comment by mattwiller** [comment]
@JaideepSingh2018 While I'm trying to troubleshoot with the `ReadAllBytes` implementation you provided, could you give me some more information to help me investigate the issue?

1. How many files are in the folder that you're trying to download?  We tested with ~200, but if your folder is substantially larger that may be contributing to the issue.
2. Are you still seeing the program hang for about 90 seconds before getting the Task Canceled error?
3. Could you please email me your API key at mwiller@box.com so I can look into if there's anything going on with your requests on the API side?

**Comment by JaideepSingh2018** [comment]
Hi Matt,

I have modified your code to work because it has some issues when I am reading file size. It only comes when client.FilesManager.GetInformationAsync(file.Id) is called. I have stripped out filling the buffer so that we can focus just on API. This code currently is breaking after reading 5-6 files

private async Task TestBoxCode(BoxFolder folder)
        {
            BoxCollection<BoxItem> items;
            System.Collections.Generic.List<BoxItem> folderItems;

            items = await client.FoldersManager.GetFolderItemsAsync(folder.Id, 500);
            folderItems = items.Entries;

            foreach (BoxItem file in folderItems)
            {
                if (file.Type == "file" )
                {
                    BoxFile fileInfo = await client.FilesManager.GetInformationAsync(file.Id);
                    byte[] buffer = new byte[fileInfo.Size.Value];
                    int position = 0;

                    var stream = await client.FilesManager.DownloadStreamAsync(file.Id);
                   }
         
            }

        }

**Comment by JaideepSingh2018** [comment]
Matt, I have sent you my API key in your mailbox. Please let me know if you need anything else to troubleshoot.

**Comment by carycheng** [comment]
Hey @JaideepSingh2018, 

We tried our best to replicate the issue that you are currently seeing. The code below is using an implementation of ReadAllBytes() similar to what you were using and it seems to working okay for us. We tested it on a folder of 211 items and observed that after running this code we ended up with 211 byte arrays. The code took about two and a half minutes to run. 

We also looked at your server logs with the API key you supplied us. We observed that there were two to six successful calls to start downloading the items and that was it. This suggests that something is possibly getting stuck in reading of the stream.

Since we cannot reproduce this issue, it would be great if you could help us do some debugging on your end to point us in the right direction. 

If you can add debug lines before and after stream.CopyTo() and .ToArray() in the implementation of ReadAllBytes() that can help us see where it might be hanging. 

If you can also try switching to [CopyToAsync()](https://msdn.microsoft.com/en-us/library/hh159084(v=vs.110).aspx) and await that call in your implementation of ReadAllBytes that would be great, thank you! 

```c#
System.Collections.Generic.List<BoxItem> folderItems;

BoxCollection<BoxItem> items = await _client.FoldersManager.GetFolderItemsAsync("FOLDER_ID", 500);
folderItems = items.Entries;

List<byte[]> files = new List<byte[]>();

foreach (BoxItem file in folderItems)
{
    byte[] fileContents;
    
    var stream = await _client.FilesManager.DownloadStreamAsync(file.Id);
    
    if (stream is MemoryStream)
    {
        fileContents = ((MemoryStream)stream).ToArray();
    } 
    else
    {
        using (var memoryStream = new MemoryStream())
        {
            stream.CopyTo(memoryStream);
            fileContents = memoryStream.ToArray();
        }
    }

    files.Add(fileContents);
}
```

**Comment by JaideepSingh2018** [comment]
Hi Cary,

Thanks for the response. Please note that if I don't even read the stream and just call following line
 var stream = await _client.FilesManager.DownloadStreamAsync(file.Id);

It will stop responding after 5-6 file.  I strongly feel you are looking in the wrong direction. Its either API or something to do with my account.

**Please note that I am using the service account to read the file contents. Here are the lines**

 items = await client.FoldersManager.GetFolderItemsAsync(folder.Id, 500);
        folderItems = items.Entries;

        foreach (BoxItem file in folderItems)
        {
            if (file.Type == "file" )
            {
         
                var stream = await client.FilesManager.DownloadStreamAsync(file.Id);
               }
     
        }

**Comment by carycheng** [comment]
Hey @JaideepSingh2018,

**Comment by JaideepSingh2018** [comment]
I just did ping and telnet test 
ping dl.boxcloud.com 
telnet dl.boxcloud.com 443
both of these gave the positive result on my machine. I am wondering if anything is blocked on our side why does even a single file downloads. If I re-run my console application it again downloads next 4-6 files and it stops. I will do postman test as well and post the results in 10 minutes

**Comment by mattwiller** [comment]
@JaideepSingh2018 Were you ever able to use Postman to test what the response from the download URL looked like?  I understand your frustration with not being able to quickly get this resolved, but without more information we don't have much to go on here — we're unable to replicate the problem on our end (even with essentially the same code) and we don't have a good way of knowing if there's some specific issue with your environment/account/etc.  If you believe we're looking in the wrong direction, it would be incredibly helpful if you could provide us with some information to show us exactly what's happening on your machine and guide us to where we should look.  Below are some suggestions for how you might go about gathering more information about exactly what's happening on your machine.

One thing we did on our end to investigate is use [Wireshark](https://www.wireshark.org/) to inspect the raw network traffic between the SDK and the Box API.  We observed the symptoms you're describing (application hanging and eventually failing with a timeout) in cases where the stream was not being actively read or something was blocking the read — that's why we're asking about potential causes along those lines.  You might be able to investigate this by adding debug statements around the stream operations in `ReadAllBytes`; I suspect that one of the synchronous operations like `.CopyTo()` might be stuck waiting for bytes from the stream and hanging the application.  You could also use Wireshark (as mentioned above) to verify that network traffic is or isn't flowing between your machine and the Box API — if it isn't that would explain why the stream is hanging.  You could also try switching to `.CopyToAsync()` if possible; this may alleviate certain types of deadlock conditions from using the synchronous copy method, but that's just a guess from me.

If you try the same code with a different account (either in the same enterprise or, does it have the same problem?  What if you try with a different folder in the original account?  Does the size of the folder affect success rate — either in number of items or size of the items in the folder?

Please let us know if any of these provides useful information or if you think of anything that might explain why this is happening for you, and we're more than happy to keep engaging with you to get this problem solved.

**Comment by JaideepSingh2018** [comment]
We can try 3 things
A) I can share my screen and we can debug together
B) why don't you connect to our test environment using our code.
C) I can share connection details with you and you can retest your code connecting to our account

Please let me know which option may work for you

**Comment by mattwiller** [comment]
@JaideepSingh2018 Unfortunately, my team is not resourced to do live debugging sessions — we need you to do some troubleshooting on your end.  The steps I provided above should be good places for you to start, and will help us narrow down where the problem might be.

As I alluded to above, could you try setting up a new test version of your app (with different credentials than your main production app) and running it against a test account with dummy files in it?  This would show if the issue is account-related, and then if you still see the problem we can check our code using your test credentials.  An important point here is that we do not want to have access to your production application or live data — for liability reasons, our team would prefer to only work with sandbox accounts and data.

**Comment by JaideepSingh2018** [comment]
Matt,

I guess you are not reading my messages completely. In order for me to read bytes or copy functions, API shall return a stream. I am getting timeout when I an trying to get the stream.
client.FilesManager.DownloadStreamAsync(file.Id);

If this function at least give result, I can try what you are recommending. This is just waste of time when you guys assumes that stream is returned by API and I am having difficulty reading bytes.

I am ready to send you the code and I want you to connect to my box account so at least we are comparing the same thing. It is such a disappointment to send the message across

**Comment by mattwiller** [comment]
@JaideepSingh2018 I'm sorry that we misunderstood where you were seeing the problem — in your original message you identified `Extensions.ReadAllBytes(await client.FilesManager.DownloadStreamAsync(fileId));` as the line that was hanging; we didn't have any way of knowing which of those two functions was causing the hang.

The [implementation of `DownloadStreamAsync()`](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxFilesManager.cs#L58) is pretty simple, but it hides a little of [how downloads work in the Box API](https://developer.box.com/v2.0/reference/#download-a-file).  There are actually two requests getting made — one to `api.box.com` which should return a 302 status code redirecting to a unique download URL.  The second request is to that download URL, on `dl.boxcloud.com`.  The stream you receive is reading bytes from this second request to `dl.boxcloud.box`.

I looked in our server logs and it looks like at least all of the requests I can see that your application is making to `api.box.com` are succeeding (getting the expected 302 status code).  I checked with our backend team that manages `dl.boxcloud.com` and they confirm that for these requests there doesn't seem to be anything wrong.  As far as our logs show, the file downloads we see you making complete correctly.  Can you try again and send us the file ID of the download that's hanging?

**Comment by JaideepSingh2018** [comment]
Hi Guys,

I was able to resolve this issue by closing the stream after I was done reading the bytes from the stream. I have put an example below.
I am not sure but may be Box have limitations about how many parallel download can happen and they are keeping track of by looking at the Stream. It just my guess..

 var stream = await client.FilesManager.DownloadStreamAsync(file.Id);
//Read bytes
stream.Close();
stream.Dispose();
