### ISSUE TITLE
Looking for advice on best practice with .NET SDK.

### ISSUE THREAD

**Issue by cbass911** [box/box-windows-sdk-v2#468]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Is best practice when uploading files to first do a preflightcheck first, if the file exists then do a preflightchecknewversion? It seems to me that it would just make sense to always do a preflightchecknewversion and skip the preflightcheck? Also when uploading a file that already exists using uploadnewversionasync, what's the best or recommended way to get the file id and etag of the existing file(s)? Thanks!

### Versions Used
.NET SDK: v2
.NET Framework/Core: 4.5

### Error Message, Including Stack Trace

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by cbass911** [comment]
Forgot to mention, I'm using VB.net but any C# code is fine as I can translate. Thanks!

**Comment by carycheng** [comment]
Hey @cbass911, 

You are correct - When uploading files it is best practice to do a preflightcheck first. If the file exists then do a preflightchecknewversion before uploading a new version of the file. 

Preflightchecknewversion cannot take the place of preflightcheck because preflightchecknewversion requires a file id and if that file does not yet exist(meaning you have not uploaded it once before) then you will not be able to just call preflightchecknewversion. 

The best way to get the file id for uploadnewversionasync is to do a `getFolderItemsAsync()` call and retrieve the item you are attempting to upload a new version for.

**Comment by cbass911** [comment]
Ok great, thank you for your response. Could you also let me know what the best way is to logout a user? I see there's a logoutasync function but I'm not sure how to call it properly. If possible could you give me a C# or VB.NET example? Thanks in advance!

**Comment by carycheng** [comment]
Hey @cbass911, 

This should achieve what you are looking for 
```C#
await client.Auth.LogoutAsync();
```

**Comment by cbass911** [comment]
That did the trick. Thank you.

**Comment by carycheng** [comment]
Excellent glad to hear @cbass911, I'm closing this issue but if you come across any other issues please don't hesitate to contact us.
