### ISSUE TITLE
Missing Serializable Attribute on BoxException

### ISSUE THREAD

**Issue by nokternol** [box/box-windows-sdk-v2#480]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
https://msdn.microsoft.com/en-us/library/ms182151.aspx
As shown in the above Microsoft documentation any exception class should have the serializable attribute applied. In debugging the BoxException object is not properly cast and looks like escaped JSON.
It is a minor issue as the exception can still be interrogated successfully.

### Versions Used
.NET SDK: 3.7.0
.NET Framework/Core: 4.6.1

### Steps to Reproduce
Cause any error in Box.V2 and capture then look at the exception in the visual studio debugger.
A conflict error would be the easiest to reproduce.. Try to do an action that has already been performed (i.e. UploadFile with a name that already exists, CreateFolder with a name that already exists)

### Error Message, Including Stack Trace
N/A
[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
Hi @nokternol — thanks for letting us know!  We'll add this to the backlog.

**Comment by mattwiller** [comment]
@nokternol Just to update on this issue, it looks like Exception did not implement `ISerializable` until .NET Standard 2.0 — since we target .NET Standard 1.6 currently with the cross-platform version of the SDK, it will be pretty difficult to add this in.  Since this isn't a major issue, it's not likely to be resolved anytime soon, at least not until we decide to bump the version of .NET Standard we target and drop support for older versions of .NET Core/Mono/Xamarin etc.  In the meantime, I'm going to close this issue since it's not under active consideration.
