### ISSUE TITLE
How do I generate an access token for server side operations?

### ISSUE THREAD

**Issue by gjdownes** [box/box-windows-sdk-v2#492]
### Description of the Issue
I set up an app in my Developer Console and used the following code as provided in the README to authenticate against the app from my server side code:

    var boxConfig = new BoxConfig(<Client_Id>, <Client_Secret>, <Enterprise_Id>, <Private_Key>, <JWT_Private_Key_Password>, <JWT_Public_Key_Id>);
    var boxJWT = new BoxJWTAuth(boxConfig);

Unfortunately, I've hit a (or thee) 10 GB service account restriction and I'm not quite sure how to get around this. I have an enterprise account, but based on Box Support, the 10GB still applies to service account. Apparently I need to hit the API using the enterprise account instead of using the service account.

The docs I've read in the repo show how to authenticate with a Developer token, but this doesn't seem practical for a production scenario. 

How can I use the SDK to generate an access token so I can start using the API as the enterprise user, and not the service account? I'm calling Box API from the server side, so a regular OAuth flow isn't an option. 

Apologies if this may seem trivial; any guidance would be appreciated.

### Versions Used
.NET SDK: 2.15.6

### Error Message
{"type":"error","status":403,"code":"storage_limit_exceeded","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Account storage limit reached","request_id":"xxx"}

**Comment by jpan-box** [comment]
Hi! Thanks for filing this. There's a couple of ways to think about your situation:

1. If you'd like, you can update that service account's 10 GB limitation to unlimited, just like you could with any other Box user. Depending on your use case, that may be the most straightforward solution. Here is the relevant command linked from our [SDK Documentation](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxUsersManager.cs#L58) and [API Documentation](https://developer.box.com/reference#update-a-users-information). You would have to do this using a token from the administrator, which can be done in two ways: using a token from your [developer console](https://github.com/box/box-windows-sdk-v2#using-a-developer-token-generate-one-in-your-app-admin-console-they-last-for-60-minutes) or generating a token for the admin using JWT Auth.

1. This gets at your question directly. If you want to get a token for the admin using JWT auth, instead of getting a token for the service account, use the code from [our example on app users](https://github.com/box/box-windows-sdk-v2#create-an-app-user). It says it's just for app users, but the same methods can be used any user in your enterprise. To do this, you will also need the "Enterprise" access (so your app can make calls for managed users/admins) and "Generate Access Tokens for Users" scopes enabled for your application in the Developer console. If you make any changes to scopes in the developer console, you must also reauthorize the application in your admin console.

1. Finally, if you decide to start using tokens for an admin user, you may also need to consider collaborations. For context, each item on Box has an owner. In your case, if you upload into a folder owned by the service account, an administrator would not be able to upload into that same folder ID unless a collaboration exists at that folder or a parent folder. You cannot create a collaboration on the root folder. You can see more about this in our [SDK Documentation](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Managers/BoxCollaborationsManager.cs) and [API Documentation](https://developer.box.com/docs/object-model#section--collaborations-https-docs-box-com-v2-0-reference-collaboration-object-).

Your question is definitely a valid one and we want to make sure we get it answered for you. However, we'd like to encourage you to try looking at or posting in our [community forums](https://community.box.com/t5/Box-Developer-Forum/bd-p/DeveloperForum) first for these types of questions, and if you believe there is a technical issue feel free to raise a support ticket. For the github issues page, we try to keep that just for issues with the SDK, versus the API in general.

Thank you!
