### ISSUE TITLE
"Bad Request" Exception Using JWT Authentication

### ISSUE THREAD

**Issue by rc6886** [box/box-windows-sdk-v2#497]
I'm using the SDK to attempt to generate a JWT to access the API. Whenever I do, I get a BoxExcepion:

> The API returned an error [BadRequest]

The description on the error in the stack trace is:

> "Please check the 'sub' claim. The 'sub' specified is invalid."

I'm using the key below saved as a JSON file:

```
{
  "boxAppSettings": {
    "clientID": "",
    "clientSecret": "",
    "appAuth": {
      "publicKeyID": "",
      "privateKey": "",
      "passphrase": ""
    }
  },
  "enterpriseID": "0"
}
```
I tried it using the following code:

```
IBoxConfig config = null;

using (var fs = new FileStream("json_key.json", FileMode.Open))
{
    config = BoxConfig.CreateFromJsonFile(fs);
}

var boxJWT = new BoxJWTAuth(config);
```

But it throws the exception when creating an instance of the **BowJWTAuth** with the config. Does anyone have any ideas on what might be causing this?

**Comment by jpan-box** [comment]
Hey @rc6886 , thanks for checking in! 

The bad request is occurring because your specified enterprise ID is 0, which is not a valid enterprise ID. You should be able to see your actual enterprise ID on the "General" page of your application within your [Developer Console](app.box.com/developers/console). If you replace the "0" with your actual enterprise ID and try again, your code should work!

At a broader level, the "sub" claim comes from the construction of the [JSON Web Token (JWT)](https://jwt.io/), which is used in [Box's implementation of JWT Authentication](https://developer.box.com/docs/construct-jwt-claim-manually). The Windows SDK here handles that construction for you, so that all you should need to pass in is a config file and then call the appropriate method for an [admin token](https://github.com/box/box-windows-sdk-v2#authenticate) or [app user token](https://github.com/box/box-windows-sdk-v2#create-an-app-user).

Finally, you'll definitely want to redact your private key, private key passphrase, and client secret! Having those out in the public would be the equivalent of publishing your passwords!

Hope that helps!

**Comment by carycheng** [comment]
Hey @rc6886, 

The "0" you are using is referring to the id of your root folder level in your Box account.

The actual id of the enterprise you can retrieve by going to Admin Console -> Gear on the top right -> Settings -> There should be a field called "Enterprise ID"

If you are the admin of your enterprise you can access the Admin console directly from the left panel in your Box account like so

<img width="197" alt="screen shot 2018-08-12 at 10 43 54 am" src="https://user-images.githubusercontent.com/6364733/44004763-d7d2fbbe-9e1c-11e8-8b36-a074743d63d0.png">

Otherwise you will need to contact the admin of that Box account.

Let us know if that works or if you have further questions, thanks!

**Comment by rc6886** [comment]
<img width="248" alt="capture" src="https://user-images.githubusercontent.com/6307249/44004865-9db46054-9e2f-11e8-91e8-2e3e062d8761.PNG">

Here's what I have for my EnterpriseID. Do I have the wrong type of account for what I'm trying to do?

**Comment by jpan-box** [comment]
Hi @rc6886 , thanks for the screenshot! What you're running into looks to be a bug with your particular plan type. 

In order to have an enterprise ID, you have to have a (free) ["developer" account](http://box.com/pricing/platform) or a paid starter and above account. In your case, it looks like you have a paid _personal_ account, which does not have an enterprise ID.

I'll open a bug to get that addressed internally, but what you'll want to do in the meantime is register for a [free box developer account](http://box.com/pricing/platform). You'll need to use a new email address, but this can be as easy as appending '+dev' to your email address. For example, if your current email is user@gmail.com, you can register with user+dev@gmail.com. Messages will go to the same inbox, but we'll treat that as a different email address. 

This will get you an entirely new box account, so if you want to access your current content, you will need to add your new user+dev@gmail.com box user as a collaborator to any existing content.

Once you get your new developer account, you can go through the same set up steps to generate your .json file once more.

Let us know if that works for you!

**Comment by rc6886** [comment]
That worked! I was able to connect.

Thank you for your help! I really appreciate it.
