### ISSUE TITLE
FoldersManager.GetInformation limits the returned item collection to 100 entries but does not support paging

### ISSUE THREAD

**Issue by ckress** [box/box-windows-sdk-v2#503]
- [ x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
A call to `FoldersManager.GetInformation(int folderId)` returns an `ItemCollection`. The `ItemCollection` holds a subset of the existing items and additionally exposes information about the `TotalCount` (reflecting the actual number of items in the folder), the `Limit` (how many items are returned in the `Entries` object), and the `Offset` (paging information).
However, there is no way to actually page through all items in a folder, since the API does not take an offset parameter. Furthermore, the limit can not be set.
We need at least an API like `FoldersManager.GetInformation(int folderId, int offset = 0)` to be able to retrieve the complete folder information via paging.

### Versions Used
.NET SDK: 2.3.9.0  
.NET Framework/Core: 4.5.2

### Steps to Reproduce
1. Create a folder on Box
2. Create a huge number of items (e.g., 101 subfolders)
3. Call `FoldersManager.GetInformation()` with the folder id
4. Only the first 100 items are returned with no way to retrieve the remaining items

![foldersmanager getinformation](https://user-images.githubusercontent.com/33691614/45877683-f6ecda00-bd9e-11e8-8383-ba2af515cf55.png)

**Comment by ckress** [comment]
So the `GetInformationAsync()` API is not going to be changed?

What is the recommended pattern then if one wants to get the Folder information as well as the FolderItem information? Make use of `GetInformationAsync()` with the `BoxFolder.FieldItemCollection` field and only make additional use of `GetFolderItemsAsync()` if the the folder item count is > 100? This would save an extra request in case of small folders.

Anyway, the item count limit in `GetInformationAsync()` should be documented. Currently it is neither documented in the [.NET SDK](https://github.com/box/box-windows-sdk-v2/blob/master/docs/folders.md#get-a-folders-items) nor in the [API reference](https://api.box.com/2.0/folders/folder_id).

**Comment by ckress** [comment]
Uups, sorry closing

**Comment by mattwiller** [comment]
@ckress The API endpoint that `GetInformationAsync()` calls cannot page through the `item_collection`; they are presented as a convenience for small folders.  The recommended pattern if you want to potentially save an API call would be to compare `folder.ItemCollection.TotalCount` (which shows the actual number of items in the folder) and `folder.ItemCollection.Entries.Count` (which is the number of items displayed in the API response).  If `TotalCount` is greater than `Count`, you'll need to call `GetFolderItemsAsync()` to get the rest of the items, otherwise you can just use the items in `folder.ItemCollection.Entries`.
