### ISSUE TITLE
"commentcount" property not returning correct number of comments

### ISSUE THREAD

**Issue by whiggs** [box/box-windows-sdk-v2#519]
### Description of the Issue
The "commentcount" property of the "boxfile" object which is returned by the "getinformation" method for the "Box.v2.managers.BoxFilesManager" object does not return the correct value.  Please see below:

![The issue](https://i.imgur.com/uFMsbpw.png)

### Versions Used
.NET SDK: v3.10.0

### Steps to Reproduce
1. use the method mentioned above to return the information of a box file that has a comment and compare the number of comments that you can count on the file with the number of comments listed for the "commentcount" property

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@whiggs The `comment_count` field is not returned from the API in the file object response by default — you'll need to request it specifically using the `fields` parameter of `getInformationAsync()`:

```c#
var fields = new string[] { "comment_count" };
var file = await client.FilesManager.GetInformationAsync(id: "11111", fields: fields);
```

You're seeing the value `0` currently because the field was originally defined as `int` when it should clearly be `int?` — since no value is assigned when the JSON (which doesn't contain the `comment_count` field) is parsed, it retains the default `int` value of `0`.
