### ISSUE TITLE
TaskAssignment request fail by box.V2

### ISSUE THREAD

**Issue by TomoyukiKumaoka** [box/box-windows-sdk-v2#529]
I tried the following sdk: 
https://github.com/box/box-windows-sdk-v2/blob/5800ee9aa621493d6d23d8628b2bf5b20057309a/docs/tasks.md#assign-task

I execute CreateTaskAssignmentAsync and it returns error, 

> Error converting value "未完了" to type 'System.Nullable`1[Box.V2.Models.ResolutionStateType]'. Path >'resolution_state', line 1, position 564. 
>Newtonsoft.Json.JsonSerializationException: Error converting value "未完了" to type >'System.Nullable`1[Box.V2.Models.ResolutionStateType]'. Path 'resolution_state', line 1, position 564. ---> >System.ArgumentException: Requested value '未完了' was not found. 

"未完了" means "Incomplete". 
but I can find on box web that the task is assigned to user without problem.

So this may be a bug with box.V2 and please check this.

Your support team said "This seems to be localization-related when SDK is trying to parse in the Task status."
So please fix this to use in Japanese environment.

Thanks,
Tomoyuki Kumaoka

**Comment by mattwiller** [comment]
@TomoyukiKumaoka Thank you for letting us know!  It looks like the issue occurs because the data in the field is actually stored as localized text, which is unexpected for the SDK.  Usually these API fields are unlocalized enum strings (in English), but in this case it seems that the API returns the localized strings.  We'll evaluate how to fix this in a backwards-compatible way and add it to our backlog!
