### ISSUE TITLE
Unable to get Token using ARC (chrome extension)

### ISSUE THREAD

**Issue by dhawkKD** [box/box-windows-sdk-v2#550]
![Body](https://user-images.githubusercontent.com/17156312/55467525-21a5ce00-561f-11e9-8a43-194c837853a1.PNG)
![Request](https://user-images.githubusercontent.com/17156312/55467526-223e6480-561f-11e9-813e-93c3cf97822f.PNG)

I am trying to get Access_Token by using ARC chrome extension to test API.

To get Token, what I am doing in ARC is:
1. https://api.box.com/oauth2/token/ hitting api on this url.
2. Method is POST
3. In Body, I have passed :
       {"grant_type"="authorization_code",&"client_id"="REDACTED",&"client_secret"="REDACTED"}
4. Passed content-type as application/x-www-form-urlencoded.

After running this I am getting error which is:
{
"error": "invalid_request",
"error_description": "Invalid grant_type parameter or parameter missing"
}

In Authorization, I have also tried with my Email and password but without any success.
Can anyone please help me in this.

**Comment by mattwiller** [comment]
@dhawkKD First, I just edited your comment to remove the client ID and secret — these shouldn't be posted publicly (especially the client secret), as they will allow anyone to impersonate your application.  If possible, you should reset your client secret immediately!

Otherwise, this doesn't look like it's an issue with the Box .NET SDK.  If you're having trouble getting started authenticating with the Box API, I would recommend starting from our [Application Setup](https://developer.box.com/docs/application-setup) documentation.  That should help guide you through the process!
