### ISSUE TITLE
BoxTaskManager.UpdateTaskAssignmentAsync does not work

### ISSUE THREAD

**Issue by mkiosugadaikichi** [box/box-windows-sdk-v2#557]
BoxTaskAssignmentUpdateRequest contains Id field.
It will be serialized and sent in request body.

But id is also specified in URI path.
Send in request body is redundant and Box returns "Error parsing input model."

**Comment by mattwiller** [comment]
@mkiosugadaikichi We looked into this issue and determined that a change in the Tasks API altered the way that the request body is parsed, resulting in the error you're seeing.  This will be fixed in the API, so I'll let you know here when the issue is resolved.  You shouldn't need to make any code changes to your application to receive the fix, once it's released in the API.

**Comment by mattwiller** [comment]
@mkiosugadaikichi The fix for this issue has been deployed in the Tasks API and it should be resolved now.  Could you please check in your application and let us know if you're still seeing any issues?

**Comment by mkiosugadaikichi** [comment]
@mattwiller I checked issue is resolved.Thank you.
