### ISSUE TITLE
When BoxGroupsManager.CreateAsync() fails due to conflicting item, ConflictingItems on the thrown BoxConflictException is null

### ISSUE THREAD

**Issue by jfhugues** [box/box-windows-sdk-v2#571]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When a call BoxGroupsManager.CreateAsync() fails do to a conflict with an existing BoxGroup, the expectation is that the ConflictingItems property of the thrown BoxConflictException should reflect the existing BoxGroup(s) which are causing the conflict, but instead ConflictingItems always appears to be null.

### Versions Used
.NET SDK: 3.17.0
.NET Framework/Core: Framework 4.6.1

### Steps to Reproduce
Call BoxGroupsManager.CreateAsync() where BoxGroupRequest.Name is known to match the Name of an existing BoxGroup.  This will throw a BoxConflictException.  The expectation then is that the ConflictingItems property of that exception should indicate the existing BoxGroup that is in conflict, but instead this value always appears to be null.

**Comment by mattwiller** [comment]
@jfhugues Unfortunately, the API does not provide this information.  The error JSON returned by the API looks like this:
```json
{
    "type": "error",
    "status": 409,
    "code": "conflict",
    "context_info": {
        "errors": [
            {
                "reason": "invalid_parameter",
                "name": "group_tag_name",
                "message": "Invalid value 'Test'. A resource with value 'Test' already exists"
            }
        ]
    },
    "help_url": "http://developers.box.com/docs/#errors",
    "message": "Resource with the same name already exists",
    "request_id": "2gph86g3rz46py3d"
}
```

The SDK attempts to read conflicting item information from the `context_info.conflicts` property, which is not present on this error.  I put in a request to see if the information can be added to the error JSON, at which point this should just work in the SDK.  Since there's nothing for us to fix in the SDK, I'm going to go ahead and close this issue.
