### ISSUE TITLE
Incorrect number of users being returned when using a limit

### ISSUE THREAD

**Issue by SeanLAllen** [box/box-windows-sdk-v2#599]
### Incorrect number of users being returned when using a limit
When calling UsersManager.GetEnterpriseUsersAsync with a limit of 1000 the number of items returned is only 306, when there are 361 users for this application. Because the limit was set to 1000, I assumed I would only get truncated results if they users exceeded 1000.

### Versions Used
.NET SDK: 3.17
.NET Framework/Core: .Net Core 2.0

### Steps to Reproduce
Create multiple applications, each with their own users and groups and folders.
The value for the total count from GetEnterpriseUsersAsync should exceed 1000.
With the count of users for the individual application to not be close to 1000, say 300.
Call UsersManager.GetEnterpriseUsersAsync(limit: 1000) 

### My workaround
To get all of the values, I needed to call GetEnterpriseUsersAsync in a loop with the offset starting at 0, and then equaling the offset plus the limit.

**Comment by carycheng** [comment]
Hello @SeanLAllen,

This seems does not seem like an SDK issue because we take the response that comes back from the API and we give it back to the user directly. We don't have any special case handling or logic in between. I think a good channel to reach out to would be Box Support, you can submit a case here with the details and they are very responsive.

Much appreciated

**Comment by PJSimon** [comment]
Hi @SeanLAllen, I'm closing this issue, but if so still need assistance, let us know and we can open it back up!  Thanks!
