### ISSUE TITLE
An error occurs in FoldersManager.GetFolderItemsAsync

### ISSUE THREAD

**Issue by shibuta-akitomo-fixer** [box/box-windows-sdk-v2#615]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
An error occurs when "date" or "size" is entered in the query parameter "sort" of FoldersManager.GetFolderItemsAsync

### Versions Used
.NET SDK: .NET SDK: Box.V2 3.20.0
.NET Framework/Core: ASP.NET Core 2.2.0
### Steps to Reproduce
Enter "date" or "size" in query parameter "sort" of "FoldersManager.GetFolderItemsAsync()"

### Error Message, Including Stack Trace
"Error converting value \"date\" to type 'Box.V2.Models.BoxSortBy'. Path 'order[1].by', line 1, position 37785."

[sdk-docs]: ./README.md
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @shibuta-akitomo-fixer,

Can you please give us your code snippet? It will better help us debug.

Thank you!

**Comment by shibuta-akitomo-fixer** [comment]
An error occurs when I run these.
`var folderItems = await client.FoldersManager.GetFolderItemsAsync(id: "0", limit: 20, sort: "date");`
`var folderItems = await client.FoldersManager.GetFolderItemsAsync(id: "0", limit: 20, sort: "size");`

**Comment by PJSimon** [comment]
Hi @shibuta-akitomo-fixer,

I apologize for the delay in responding.  My team is still catching up from the holiday season.  Are you still having this issue?

I took a look at the `GetFolderItemsAsync` method in the SDK and it looks like you're calling it correctly.  
`var folderItems = await client.FoldersManager.GetFolderItemsAsync(id: "0", limit: 20, sort: "date");`
`var folderItems = await client.FoldersManager.GetFolderItemsAsync(id: "0", limit: 20, sort: "size");`

The error message:
`"Error converting value "date" to type 'Box.V2.Models.BoxSortBy'. Path 'order[1].by', line 1, position 37785."`
is confusing though, because the `sort` parameter is a `String` and not a `BoxSortBy` enum type.  So I'm not sure where that error message is coming from.

Would you be able to send a full stack trace associated with this error?  That will help me try to find where it's happening.  Thanks!

Patrick

**Comment by PJSimon** [comment]
Hi @shibuta-akitomo-fixer,

We haven't heard back from you in a while.  I hope you were able to resolve this.  I'm going to close the issue for now.  If you still need assistance, just re-open this issue and we'll pick it up from there.

Best,

Patrick
