### ISSUE TITLE
GetFolderItemsAsync only exposes the ModifiedAt attribute when it should expose the ContentModifiedAt attribute

### ISSUE THREAD

**Issue by zakbox** [box/box-windows-sdk-v2#632]
I have checked that the [SDK documentation](https://github.com/box/box-windows-sdk-v2/issues/README.md) and [API documentation](https://developer.box.com/docs) doesn't solve my issue.

### Description of the Issue
Currently, the GetFolderItemsAsync call does not expose the ContentModifiedAt attribute, and instead exposes the ModifiedAt attribute. This attribute is a value for when a file has changed _on Box's servers_. This value is largely irrelevant for customers, as they would find the ContentModifiedAt attribute (when the file contents were modified) to be more helpful. This was found when a re-key for a KeySafe enabled account led to them thinking the files were modified when in fact the file contents were not modified and the only item that was changed was the key value for the files (a change that only occurs on Box servers).

This issue is a request to expose the ContentModifiedAt value with a GetFolderItemsAsync call instead of, or in addition to, the ModifiedAt attribute.

### Versions Used
.NET SDK:  Box.V2 3.9.3

**Comment by sujaygarlanka** [comment]
Hey @zakbox,
`GetFolderItemsAsync` returns a `BoxItem`. `BoxItem` can be a folder, file, or weblink, so it has attributes that all these items have. Since `ContentModifiedAt` is a field that only folder and files have, we don't want to add it to `BoxItem`. If we do add it, we would have to make an exception for this field and it would contradict our existing design. The best way around this would be to make an additional `GetInformationAsync`. Sorry, I know this is less efficient, but this the only solution right now. I hope this helps!
