### ISSUE TITLE
BoxJWTAuth.AdminToken:No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by getandplay** [box/box-windows-sdk-v2#637]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I created a Box App. Every time I call BoxJWTAuth.AdminToken() will throw an exception.

### System.AggregateException: 'One or more errors occurred. (No connection could be made because the target machine actively refused it.)'

Here is my json content

```json
{
  "boxAppSettings": {
    "clientID": "l8djg4y9krdg12c9kakhiro255t3is5h",
    "clientSecret": "2gA3XjD3phOD6u3Sqz3PilQhYTNGrCFc",
    "appAuth": {
      "publicKeyID": "",
      "privateKey": "",
      "passphrase": ""
    }
  },
  "enterpriseID": "306877865"
}
```

Here is my code

```csharp
           var boxConfig = BoxConfig.CreateFromJsonString(GetConfigJson());
            // Set web proxy
            boxConfig.WebProxy = new BoxHttpProxy();
            var boxJWT = new BoxJWTAuth(boxConfig);
            var adminToken = boxJWT.AdminToken();
            var adminClient = boxJWT.AdminClient(adminToken);
            //var http = new HttpListener();
```

![image](https://user-images.githubusercontent.com/3829760/75590516-22b7c900-5a43-11ea-93e0-c8fc321ad45c.png)

### Versions Used
.NET SDK: .Net Core 3.1
.NET Framework/Core:  .Net Core 3.1

### Error Message, Including Stack Trace
One or more errors occurred. (No connection could be made because the target machine actively refused it.)

**Comment by tjones0808** [comment]
also getting an error with AdminToken: error "Method Not Supported", any ideas?

**Comment by PJSimon** [comment]
@getandplay & @tjones0808, thank you for this issue.  We will take a look ASAP and get back to you soon.  Thanks!

**Comment by sujaygarlanka** [comment]
@getandplay The connection error you are facing most likely has to do with your firewall or some other network issue on your end. This stack overflow post may help, https://stackoverflow.com/questions/2972600/no-connection-could-be-made-because-the-target-machine-actively-refused-it.

**Comment by sujaygarlanka** [comment]
@tjones0808 `AdminToken` is definitely a method on `BoxJWTAuth()`. Perhaps, your `BoxJWTAuth` object is not being correctly instantiated. If you can post your logs, that would be very helpful.

**Comment by sujaygarlanka** [comment]
> also getting an error with AdminToken: error "Method Not Supported", any ideas?

AdminToken is definitely a method on BoxJWTAuth(). Perhaps, your BoxJWTAuth object is not being correctly instantiated. If you can post your logs, that would be very helpful.

**Comment by PJSimon** [comment]
@tjones0808 Were you able to make any progress?  If so, please re-open this issue and we'll go from there!  Thanks!

**Comment by tjones0808** [comment]
@PJSimon hey yes I was able to get passed this. I think it was just my app permissions need approval. Thanks for the help!

**Comment by linehammer** [comment]
Generally, it happens that something is preventing a connection to the port or hostname. Either there is a firewall blocking the connection or the process that is hosting the service is not listening on that specific port. This may be because it is not running at all or because it is listening on a different port.

Try running netstat -anb from the command line to see if there's anything listening on the port you were entered. If you get nothing, try changing your port number and see if that works for you.  In Windows operating systems, you can use the netstat services via the command line (cmd.exe) . On Linux you may need to do netstat -anp instead.

The target machine [actively refused](http://csharp.net-informations.com/communications/connection.htm) it occasionally , it is likely because the server has a full 'backlog' . Regardless of whether you can increase the server backlog , you do need retry logic in your client code, sometimes it cope with this issue; as even with a long backlog the server might be receiving lots of other requests on that port at that time.
