### ISSUE TITLE
how to know if the file is marked as favorites using .Net sdk

### ISSUE THREAD

**Issue by bmanju544** [box/box-windows-sdk-v2#641]
how to know if the file is marked as favorites and is there any method to get all favorites

**Comment by carycheng** [comment]
Hey @bmanju544,

You can use the get all collections endpoint first and then specify the favorites collection id in order to retrieve all files marked as favorites. For documentation please refer to here:

1. [Retrieve all collections](https://github.com/box/box-windows-sdk-v2/blob/master/docs/collections.md#get-a-users-collections)
2. [Get items in specified collection](https://github.com/box/box-windows-sdk-v2/blob/master/docs/collections.md#get-the-items-in-a-collection)

Please let us know if this is what you were looking for, thanks!

**Comment by sujaygarlanka** [comment]
If you have any issues with this, you can re-open this issue.
