### ISSUE TITLE
How to get all the file versions with content using .Net sdk

### ISSUE THREAD

**Issue by bmanju544** [box/box-windows-sdk-v2#642]
How to get all the file versions with content using .Net sdk and getting file content by version no.

**Comment by carycheng** [comment]
Hey @bmanju544,

In order to retrieve all file versions please refer to this endpoint [here](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#get-previous-file-versions). After you retrieve all versions for a file you can take actions on it such as:

- [Promote old version to current version](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#promote-version)
- [Delete old version](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#delete-a-previous-file-version)
- [Download previous version](https://github.com/box/box-windows-sdk-v2/blob/master/docs/files.md#download-a-previous-version-of-a-file)

Please let us know if this is helpful, thanks!

**Comment by sujaygarlanka** [comment]
If you have any issues with this, you can re-open this issue.
