### ISSUE TITLE
Separate release scripts from SDK source

### ISSUE THREAD

**Issue by robgwinkler** [box/box-windows-sdk-v2#787]
I would like the Release Scripts (from chores 770, 772, 783) to be separated from the main solution file. As they require understandably private files (key files) and other restricted implementation details (nuget package information), this should be separated into its own Build Solution file so that the main SDK solution remains Release build capable without changes.

**Comment by arjankowski** [comment]
Hi @robgwinkler,

Thanks for submitting this Issue! 
We will take a look at your proposal and get back to you ASAP!

@arjankowski

**Comment by mwwoda** [comment]
HI @robgwinkler 

Sorry for such a late reply. These scripts are tightly coupled to the SDK, so I don't see a reason to move them outside of this repo. Additionally, they can still be used with mock data or in dry run mode to test the release process. Building the solution in Release configuration should still be possible, as we have a separate build configuration called SignedRelease for the script purposes.

I am closing this issue because we are not considering this enhancement at the moment, but if you want to discuss it further, feel free to reopen it and give your thoughts on the topic.
