### ISSUE TITLE
Can I use this sdk in unity. I am not able to get get access token using jwtauth.

### ISSUE THREAD

**Issue by Suman-298** [box/box-windows-sdk-v2#836]
- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Versions Used
.Net SDK: 
Windows: 

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by mhagmajer** [comment]
Hello @Suman-298, thanks for posting the issue! We're looking into it

**Comment by arjankowski** [comment]
Thanks @Suman-298 for submitting this issue, I will try to help with it.

But first, I have some questions:

1) Can you show me your code, which you use to get access token?
2) What exactly has happened, that you can not get access token? Is this because of exception during getting token? Can you show me this error/exception?
3) Have you read this [doc page](https://github.com/box/box-windows-sdk-v2/blob/main/docs/authentication.md#server-auth-with-jwt) with using JWT? 

Maybe this would help.
