### ISSUE TITLE
storage_limit_exceeded - Account storage limit reached

### ISSUE THREAD

**Issue by Abdullateef91** [box/box-windows-sdk-v2#868]
### Description of the Issue
Yesterday it occurs the first time, but that time i was in hurry i have deleted some files from boxstorage and have found out a setting in >>Enterprise Settings - >> User Settings >> storage limit - so i made changes there and get unlimited but still the same error is happening after 10GB i have account with business plan and assuming after taking it why it's happening like that, it also shows that i have unlimited storage but on the other hand "it is popping storage limit reached".

I am attaching you some screenshots for it. Kindly guide me what can i do, that this barrier will be removed. Thanks.
![boxStorageError](https://user-images.githubusercontent.com/57285622/205207490-caba4dba-9867-4ba4-97f0-806b1ccd1aac.JPG)
![StorageEnterprise](https://user-images.githubusercontent.com/57285622/205207942-3ca882f5-45e5-4323-817c-e0587a825c54.JPG)
![StorageProve](https://user-images.githubusercontent.com/57285622/205207959-fea0d888-a5a0-49bc-b02f-3c7f296991a0.JPG)

### Error Message, Including Stack Trace
The API returned an error [Forbidden | u4741jh8pagfhtdv.] storage_limit_exceeded - Account storage limit reached

### Versions Used
.Net SDK: 
Windows: 

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by antusus** [comment]
Hello @Abdullateef91 ,

It is not an SDK error but application configuration. Verify that this application is connected to proper account, maybe try reauthorising it so that it will refresh state. You can try and create a new one to check if the new one can upload. You can also follow this guide:
https://support.box.com/hc/en-us/articles/360044193293-API-Uploads-Account-Storage-Limit-Reached
If this would not help reach out to support:
https://support.box.com/hc/en-us/requests/new
