### ISSUE TITLE
Cannot get Folders only from .NET SDK

### ISSUE THREAD

**Issue by tnlthanzeel** [box/box-windows-sdk-v2#887]
Hi all, we are using the .NET SDK to connect to Box. We are using the `boxClient.FoldersManager.GetFolderItemsAsync(folderId, 100);`.

The problem is this Get request returns files and folders, but there is not way filter only for Folders from the `FoldersManager.GetFolderItemsAsync(folderId, 100);`. We tried the `SearchManager` , the problem with `SearchManager` is it needs a query and a it returns all the subfolders.

Why is it not possible to just get folders only from `FoldersManager` without files?

**Comment by antusus** [comment]
Hi @tnlthanzeel,
this is expected behaviour of getting items in folder. It is stated in the documentation of this method:
`Retrieves the files and/or folders contained within this folder without any other metadata about the folder. `
It is using this API and it can return Files, Folders and WebLinks
https://developer.box.com/reference/get-folders-id-items/
you cannot get only folder items using this method.

If you want you can reach out [here](https://pulse.box.com/forums/909778-product-feedback) and suggest a change for the API.

**Comment by tnlthanzeel** [comment]
is it not possible to simply add a filter in the backend so that we can pass a query string parameter and get filtered data?

**Comment by antusus** [comment]
The SDK team is building wrappers for existing APIs. We cannot change backend. That is why I'm suggesting to reach out to [Box Pulse](https://pulse.box.com/forums/909778-product-feedback). This way you can submit feedback to the product and talk possible solutions.

**Comment by tnlthanzeel** [comment]
okay noted!. thanks
