### ISSUE TITLE
DownloadAsync - Returned stream hangs when writing to disk

### ISSUE THREAD

**Issue by tivanyo-verqu** [box/box-windows-sdk-v2#917]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
We're iterating through a Box environment and downloading any files that meet our search criteria. The vast majority of these files are able to be downloaded without any issue, but we noticed the application "hangs" for days preventing it from running to completion. Below is a code snippet that we are using.

```
using (FileStream fileStream = new FileStream(safeTempPath, FileMode.CreateNew, FileAccess.Write, FileShare.Read))
{
	using Stream stream = await boxClient.FilesManager.DownloadAsync(boxFile.Id, timeout: APITimeout).ConfigureAwait(false);
	await stream.CopyToAsync(fileStream, _tokenSource.Token);

	stream.Close();
	stream.Dispose();
}
```

The stream gets stuck when we call the **CopyToAsync** method. We originally  had our own buffer reader/writer but switched it over to use **CopyToAsync** which had the same results – one file gets stuck and doesn’t move forward.

1. Could this be caused due to a file that is too large? Would we need to change how we call **DownloadAsync**  to instead use a loop and pass in values for _startOffsetInBytes_ and _endOffsetInBytes_
2. Is there another preferred method for writing the return stream to disk that Box recommends?

### Steps to Reproduce
Sadly we're not seeing this happen to the same file each time and we're unable to reproduce it within our own environment. 

### Expected Behavior
When we call the **DownloadAsync** SDK method, we can then write the returned stream to a FileStream

### Error Message, Including Stack Trace
No errors are thrown, the application simply hangs

### Versions Used
.Net SDK: 4.2.0
Windows: Windows Server Core 2019

[sdk-docs]: ./docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by mhagmajer** [comment]
Thanks for posting the issue, we'll discuss it within the team and get back to you

**Comment by mwwoda** [comment]
Hi @tivanyo-verqu 
The problem most likely occurs because the connection has been affected (e.g. broken) in the middle of operation and `DownloadAsync` has not returned the entire contents of the file. `CopyAsync` does not know that, and it's still trying to read the stream indefinitely. You can simulate a similar scenario by aborting the internet connection in the middle of `CopyAsync`.

There are several things you can do. If you are still trying to use `CopyAsync`, you can try using the `cancellationToken` you pass to it. You can use the [CancelAfter](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=net-7.0) function to make it behave like a timeout. In the case of TaskCancelled exception, you could retry the download request. Another solution would be to read the stream bit by bit and see if it contains the entire file.
